spring:
  server:
    port: 9093
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:paymentdb
    username: chandan
    password: chandan
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/span
logging:
  pattern:
    level: "%5p [${spring.application.name:}] traceId=%X{traceId:-} spanId=%X{spanId:-}"
